import { useState } from 'react';
import { Hammer, Zap } from 'lucide-react';
import { Boulder, Pebble } from '@/lib/types';
import { generateId } from '@/lib/store';
import { toast } from 'sonner';
import { useProStatus } from '@/hooks/useProStatus';
import UpgradeModal from './UpgradeModal';

interface AutoHammerProps {
  spark: string;
  onGenerated: (boulders: Boulder[]) => void;
}

// Free tier: template generic (tanpa AI)
function generateFreeTemplate(spark: string): Boulder[] {
  return [
    { id: generateId(), title: 'Research & Planning', pebbles: ['Define scope and goals', 'Research existing solutions', 'Create rough outline'].map(text => ({ id: generateId(), text, status: 'todo' as Pebble['status'] })) },
    { id: generateId(), title: 'Foundation', pebbles: ['Set up basic structure', 'Define core components', 'Create initial prototype'].map(text => ({ id: generateId(), text, status: 'todo' as Pebble['status'] })) },
    { id: generateId(), title: 'Build & Iterate', pebbles: ['Implement core features', 'Test and refine', 'Gather early feedback'].map(text => ({ id: generateId(), text, status: 'todo' as Pebble['status'] })) },
    { id: generateId(), title: 'Polish & Ship', pebbles: ['Final review and cleanup', 'Prepare for launch', 'Ship it!'].map(text => ({ id: generateId(), text, status: 'todo' as Pebble['status'] })) },
  ];
}

const AutoHammer = ({ spark, onGenerated }: AutoHammerProps) => {
  const [isHammering, setIsHammering] = useState(false);
  const [showUpgrade, setShowUpgrade] = useState(false);
  const { isPro, isTrialing, trialDaysLeft, activatePro } = useProStatus();

  const hammerWithAI = async () => {
    setIsHammering(true);
    try {
      const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
      if (!apiKey) throw new Error('API key tidak ditemukan. Cek file .env kamu!');

      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{
              parts: [{
                text: `You are an expert project planner. Your job is to break down a project idea into concrete, actionable phases and tasks.

                  Project idea: "${spark}"

                  IMPORTANT RULES:
                  - Read the project idea carefully and tailor EVERYTHING specifically to it
                  - Phase titles must reflect actual stages of THIS specific project, not generic names
                  - Tasks must be concrete actions someone would actually do for THIS project
                  - No generic tasks like "Research existing solutions" or "Gather feedback" unless truly relevant
                  - Use the same language as the project idea (if idea is in Indonesian, respond in Indonesian)
                  - Be specific: instead of "Build core features", say "Build login & authentication system"

                  Return ONLY a valid JSON array, no explanation, no markdown, no backticks:
                  [
                    {
                      "title": "Phase name specific to this project",
                      "pebbles": ["Specific task 1", "Specific task 2", "Specific task 3"]
                    }
                  ]

                  Constraints:
                  - 3 to 5 phases
                  - 2 to 4 tasks per phase
                  - Every single item must be directly relevant to: "${spark}"`,
              }],
            }],
            generationConfig: { temperature: 0.7, maxOutputTokens: 2000 },
          }),
        }
      );

      if (!response.ok) {
        const err = await response.json();
        throw new Error(err?.error?.message || 'Request ke Gemini API gagal');
      }

      const data = await response.json();
      const raw = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
      const match = raw.match(/\[[\s\S]*\]/);
      if (!match) throw new Error('Format response tidak valid');
      const parsed = JSON.parse(match[0]);

      const boulders: Boulder[] = parsed.map((phase: { title: string; pebbles: string[] }) => ({
        id: generateId(),
        title: phase.title,
        pebbles: phase.pebbles.map((text: string) => ({
          id: generateId(), text, status: 'todo' as Pebble['status'],
        })),
      }));

      onGenerated(boulders);
      toast.success('Boulders & pebbles generated by AI! ✨');
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Terjadi kesalahan';
      toast.error(`AutoHammer gagal: ${message}`);
    } finally {
      setIsHammering(false);
    }
  };

  const hammer = async () => {
    if (isPro) {
      await hammerWithAI();
    } else {
      // Free tier: pakai template
      const boulders = generateFreeTemplate(spark);
      onGenerated(boulders);
      toast.info('Menggunakan template. Upgrade ke Pro untuk hasil yang lebih relevan dengan AI!');
    }
  };

  return (
    <>
      <div className="flex items-center gap-2">
        {/* Tombol Auto Hammer */}
        <button
          onClick={hammer}
          disabled={isHammering}
          className="flex items-center gap-2 px-4 py-2 text-sm font-body bg-foreground text-background rounded-md hover:opacity-90 transition-opacity disabled:opacity-50 whitespace-nowrap shrink-0"
        >
          <Hammer size={14} className={isHammering ? 'animate-bounce' : ''} />
          {isHammering ? 'Hammering…' : isPro ? 'Auto Hammer' : 'Auto Hammer'}
        </button>
      </div>

      {/* Upgrade Modal */}
      {showUpgrade && (
        <UpgradeModal
          onClose={() => setShowUpgrade(false)}
          onSuccess={activatePro}
        />
      )}
    </>
  );
};

export default AutoHammer;