import { useState } from 'react';
import { Hammer } from 'lucide-react';
import { Boulder, Pebble } from '@/lib/types';
import { generateId } from '@/lib/store';
import { toast } from 'sonner';
import { useProStatus } from '@/hooks/useProStatus';
import UpgradeModal from './UpgradeModal';
import { callAI, parseJsonArray, buildAutoHammerPrompt } from '@/lib/ai';

interface AutoHammerProps {
  spark: string;
  onGenerated: (boulders: Boulder[]) => void;
}

function generateFreeTemplate(): Boulder[] {
  return [
    { id: generateId(), title: 'Research & Planning', pebbles: ['Define scope and goals', 'Research existing solutions', 'Create rough outline'].map(text => ({ id: generateId(), text, status: 'todo' as Pebble['status'] })) },
    { id: generateId(), title: 'Foundation', pebbles: ['Set up basic structure', 'Define core components', 'Create initial prototype'].map(text => ({ id: generateId(), text, status: 'todo' as Pebble['status'] })) },
    { id: generateId(), title: 'Build & Iterate', pebbles: ['Implement core features', 'Test and refine', 'Gather early feedback'].map(text => ({ id: generateId(), text, status: 'todo' as Pebble['status'] })) },
    { id: generateId(), title: 'Polish & Ship', pebbles: ['Final review and cleanup', 'Prepare for launch', 'Ship it!'].map(text => ({ id: generateId(), text, status: 'todo' as Pebble['status'] })) },
  ];
}

const AutoHammer = ({ spark, onGenerated }: AutoHammerProps) => {
  const [isHammering, setIsHammering] = useState(false);
  const [showUpgrade, setShowUpgrade] = useState(false);
  const { isPro, activatePro } = useProStatus();

  const hammerWithAI = async () => {
    setIsHammering(true);
    try {
      const raw = await callAI(buildAutoHammerPrompt(spark), { temperature: 0.7, maxTokens: 2000 });

      const match = raw.match(/\[[\s\S]*\]/);
      if (!match) throw new Error('Format response tidak valid');
      const parsed = JSON.parse(match[0]);

      const boulders: Boulder[] = parsed.map((phase: { title: string; pebbles: string[] }) => ({
        id: generateId(),
        title: phase.title,
        pebbles: phase.pebbles.map((text: string) => ({
          id: generateId(), text, status: 'todo' as Pebble['status'],
        })),
      }));

      onGenerated(boulders);
      toast.success('Boulders & pebbles generated by AI! ✨');
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Terjadi kesalahan';
      toast.error(`AutoHammer gagal: ${message}`);
    } finally {
      setIsHammering(false);
    }
  };

  const hammer = async () => {
    if (isPro) {
      await hammerWithAI();
    } else {
      const boulders = generateFreeTemplate();
      onGenerated(boulders);
      toast.info('Menggunakan template. Upgrade ke Pro untuk hasil AI yang relevan!');
    }
  };

  return (
    <>
      <button
        onClick={hammer}
        disabled={isHammering}
        className="flex items-center gap-2 px-4 py-2 text-sm font-body bg-foreground text-background rounded-md hover:opacity-90 transition-opacity disabled:opacity-50 whitespace-nowrap shrink-0"
      >
        <Hammer size={14} className={isHammering ? 'animate-bounce' : ''} />
        {isHammering ? 'Hammering…' : 'Auto Hammer'}
      </button>

      {showUpgrade && (
        <UpgradeModal
          onClose={() => setShowUpgrade(false)}
          onSuccess={activatePro}
        />
      )}
    </>
  );
};

export default AutoHammer;